name: Feature request
description: Sugerir uma funcionalidade nova ou melhoria
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: Que problema isso resolve
      description: Qual é a dor/limitação atual que motiva esse pedido?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposta
      description: Como você imagina que isso funcionaria?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
    validations:
      required: false
